// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/broker/broker.proto

package go_micro_service_broker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Broker service

func NewBrokerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Broker service

type BrokerService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Broker_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Broker_PingPongService, error)
}

type brokerService struct {
	c    client.Client
	name string
}

func NewBrokerService(name string, c client.Client) BrokerService {
	return &brokerService{
		c:    c,
		name: name,
	}
}

func (c *brokerService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Broker.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Broker_StreamService, error) {
	req := c.c.NewRequest(c.name, "Broker.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &brokerServiceStream{stream}, nil
}

type Broker_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type brokerServiceStream struct {
	stream client.Stream
}

func (x *brokerServiceStream) Close() error {
	return x.stream.Close()
}

func (x *brokerServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *brokerServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *brokerServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *brokerServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *brokerService) PingPong(ctx context.Context, opts ...client.CallOption) (Broker_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Broker.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &brokerServicePingPong{stream}, nil
}

type Broker_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type brokerServicePingPong struct {
	stream client.Stream
}

func (x *brokerServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *brokerServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *brokerServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *brokerServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *brokerServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *brokerServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Broker service

type BrokerHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Broker_StreamStream) error
	PingPong(context.Context, Broker_PingPongStream) error
}

func RegisterBrokerHandler(s server.Server, hdlr BrokerHandler, opts ...server.HandlerOption) error {
	type broker interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Broker struct {
		broker
	}
	h := &brokerHandler{hdlr}
	return s.Handle(s.NewHandler(&Broker{h}, opts...))
}

type brokerHandler struct {
	BrokerHandler
}

func (h *brokerHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.BrokerHandler.Call(ctx, in, out)
}

func (h *brokerHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.BrokerHandler.Stream(ctx, m, &brokerStreamStream{stream})
}

type Broker_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type brokerStreamStream struct {
	stream server.Stream
}

func (x *brokerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *brokerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *brokerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *brokerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *brokerStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *brokerHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.BrokerHandler.PingPong(ctx, &brokerPingPongStream{stream})
}

type Broker_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type brokerPingPongStream struct {
	stream server.Stream
}

func (x *brokerPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *brokerPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *brokerPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *brokerPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *brokerPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *brokerPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
