// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/serverdemo/serverdemo.proto

package go_micro_service_serverdemo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Serverdemo service

func NewServerdemoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Serverdemo service

type ServerdemoService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Serverdemo_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Serverdemo_PingPongService, error)
	HelloWorld(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type serverdemoService struct {
	c    client.Client
	name string
}

func NewServerdemoService(name string, c client.Client) ServerdemoService {
	return &serverdemoService{
		c:    c,
		name: name,
	}
}

func (c *serverdemoService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Serverdemo.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverdemoService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Serverdemo_StreamService, error) {
	req := c.c.NewRequest(c.name, "Serverdemo.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &serverdemoServiceStream{stream}, nil
}

type Serverdemo_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type serverdemoServiceStream struct {
	stream client.Stream
}

func (x *serverdemoServiceStream) Close() error {
	return x.stream.Close()
}

func (x *serverdemoServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverdemoServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverdemoServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverdemoServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverdemoService) PingPong(ctx context.Context, opts ...client.CallOption) (Serverdemo_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Serverdemo.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &serverdemoServicePingPong{stream}, nil
}

type Serverdemo_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type serverdemoServicePingPong struct {
	stream client.Stream
}

func (x *serverdemoServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *serverdemoServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *serverdemoServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverdemoServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverdemoServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *serverdemoServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverdemoService) HelloWorld(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Serverdemo.HelloWorld", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Serverdemo service

type ServerdemoHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Serverdemo_StreamStream) error
	PingPong(context.Context, Serverdemo_PingPongStream) error
	HelloWorld(context.Context, *Request, *Response) error
}

func RegisterServerdemoHandler(s server.Server, hdlr ServerdemoHandler, opts ...server.HandlerOption) error {
	type serverdemo interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
		HelloWorld(ctx context.Context, in *Request, out *Response) error
	}
	type Serverdemo struct {
		serverdemo
	}
	h := &serverdemoHandler{hdlr}
	return s.Handle(s.NewHandler(&Serverdemo{h}, opts...))
}

type serverdemoHandler struct {
	ServerdemoHandler
}

func (h *serverdemoHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ServerdemoHandler.Call(ctx, in, out)
}

func (h *serverdemoHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ServerdemoHandler.Stream(ctx, m, &serverdemoStreamStream{stream})
}

type Serverdemo_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type serverdemoStreamStream struct {
	stream server.Stream
}

func (x *serverdemoStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serverdemoStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverdemoStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverdemoStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverdemoStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *serverdemoHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ServerdemoHandler.PingPong(ctx, &serverdemoPingPongStream{stream})
}

type Serverdemo_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type serverdemoPingPongStream struct {
	stream server.Stream
}

func (x *serverdemoPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *serverdemoPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serverdemoPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serverdemoPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serverdemoPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *serverdemoPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *serverdemoHandler) HelloWorld(ctx context.Context, in *Request, out *Response) error {
	return h.ServerdemoHandler.HelloWorld(ctx, in, out)
}
